class Exception_Finally 
{
	public static void main(String[] args) 
	{
		System.out.println(count());
	}
	public static int count()
	{
		try
		{
			return 1;
		}
		catch (Exception e)
		{
			return 2;
		}
		finally
		{
			System.out.println("it will executed: ");
		}
	}
}
